-- MySQL Script generated by MySQL Workbench
-- Mon Apr  5 18:03:43 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema drive_school
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema drive_school
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `drive_school` DEFAULT CHARACTER SET utf8 ;
USE `drive_school` ;

-- -----------------------------------------------------
-- Table `drive_school`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drive_school`.`users` (
  `id` INT NOT NULL,
  `login` VARCHAR(32) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(32) NOT NULL,
  `middle_name` VARCHAR(32) NULL,
  `last_name` VARCHAR(32) NOT NULL,
  `phone_number` VARCHAR(20) NOT NULL,
  `email` VARCHAR(32) NOT NULL,
  `pass_number` VARCHAR(10) NOT NULL,
  `registration_date` DATE NOT NULL,
  `role` VARCHAR(1) NOT NULL DEFAULT 's' COMMENT 's = student\ni = instructor',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  UNIQUE INDEX `phone_number_UNIQUE` (`phone_number` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `pass_number_UNIQUE` (`pass_number` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `drive_school`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drive_school`.`groups` (
  `id` INT NOT NULL,
  `group_name` VARCHAR(20) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `group_name_UNIQUE` (`group_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `drive_school`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drive_school`.`students` (
  `users_id` INT NOT NULL,
  `study_start_date` DATE NOT NULL,
  `exam_date` DATE NOT NULL,
  `groups_id` INT NOT NULL,
  INDEX `fk_students_users_idx` (`users_id` ASC) VISIBLE,
  UNIQUE INDEX `users_id_UNIQUE` (`users_id` ASC) VISIBLE,
  INDEX `fk_students_groups1_idx` (`groups_id` ASC) VISIBLE,
  PRIMARY KEY (`users_id`),
  CONSTRAINT `fk_students_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `drive_school`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_groups1`
    FOREIGN KEY (`groups_id`)
    REFERENCES `drive_school`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `drive_school`.`instructors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drive_school`.`instructors` (
  `users_id` INT NOT NULL,
  `hired_date` DATE NOT NULL,
  `salary` INT NOT NULL,
  `last_holiday_start_date` DATE NULL,
  `last_holiday_end_date` DATE NULL,
  INDEX `fk_instructors_users1_idx` (`users_id` ASC) VISIBLE,
  UNIQUE INDEX `users_id_UNIQUE` (`users_id` ASC) VISIBLE,
  PRIMARY KEY (`users_id`),
  CONSTRAINT `fk_instructors_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `drive_school`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `drive_school`.`lesson_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drive_school`.`lesson_types` (
  `id` INT NOT NULL,
  `name` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `drive_school`.`auditories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drive_school`.`auditories` (
  `number` INT NOT NULL,
  PRIMARY KEY (`number`),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `drive_school`.`cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drive_school`.`cars` (
  `id` INT NOT NULL,
  `model` VARCHAR(32) NULL,
  `plate` VARCHAR(20) NOT NULL,
  `bought_date` DATE NOT NULL,
  `bought_price` INT NULL,
  `status` VARCHAR(32) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `plate_UNIQUE` (`plate` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `drive_school`.`lessons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drive_school`.`lessons` (
  `id` INT NOT NULL,
  `groups_id` INT NOT NULL,
  `instructors_users_id` INT NOT NULL,
  `lesson_types_id` INT NOT NULL,
  `auditories_number` INT NOT NULL,
  `cars_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_lessons_groups1_idx` (`groups_id` ASC) VISIBLE,
  INDEX `fk_lessons_instructors1_idx` (`instructors_users_id` ASC) VISIBLE,
  INDEX `fk_lessons_lesson_types1_idx` (`lesson_types_id` ASC) VISIBLE,
  INDEX `fk_lessons_auditories1_idx` (`auditories_number` ASC) VISIBLE,
  INDEX `fk_lessons_cars1_idx` (`cars_id` ASC) VISIBLE,
  CONSTRAINT `fk_lessons_groups1`
    FOREIGN KEY (`groups_id`)
    REFERENCES `drive_school`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lessons_instructors1`
    FOREIGN KEY (`instructors_users_id`)
    REFERENCES `drive_school`.`instructors` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lessons_lesson_types1`
    FOREIGN KEY (`lesson_types_id`)
    REFERENCES `drive_school`.`lesson_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lessons_auditories1`
    FOREIGN KEY (`auditories_number`)
    REFERENCES `drive_school`.`auditories` (`number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lessons_cars1`
    FOREIGN KEY (`cars_id`)
    REFERENCES `drive_school`.`cars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
