-- MySQL Script generated by MySQL Workbench
-- Tue Jun 22 21:21:52 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema drive_school
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `drive_school` ;

-- -----------------------------------------------------
-- Schema drive_school
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `drive_school` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `drive_school` ;

-- -----------------------------------------------------
-- Table `drive_school`.`auditories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `drive_school`.`auditories` ;

CREATE TABLE IF NOT EXISTS `drive_school`.`auditories` (
  `number` INT NOT NULL,
  PRIMARY KEY (`number`),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `drive_school`.`cars`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `drive_school`.`cars` ;

CREATE TABLE IF NOT EXISTS `drive_school`.`cars` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(32) NULL DEFAULT NULL,
  `plate` VARCHAR(20) NOT NULL,
  `bought_date` DATE NULL DEFAULT NULL,
  `bought_price` INT NULL DEFAULT NULL,
  `status` VARCHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `plate_UNIQUE` (`plate` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `drive_school`.`instructors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `drive_school`.`instructors` ;

CREATE TABLE IF NOT EXISTS `drive_school`.`instructors` (
  `users_id` INT NOT NULL,
  `hired_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `salary` INT NOT NULL,
  `last_holiday_start_date` DATE NULL DEFAULT NULL,
  `last_holiday_end_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`users_id`),
  UNIQUE INDEX `users_id_UNIQUE` (`users_id` ASC) VISIBLE,
  INDEX `fk_instructors_users1_idx` (`users_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `drive_school`.`lesson_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `drive_school`.`lesson_types` ;

CREATE TABLE IF NOT EXISTS `drive_school`.`lesson_types` (
  `id` INT NOT NULL,
  `name` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `drive_school`.`study_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `drive_school`.`study_groups` ;

CREATE TABLE IF NOT EXISTS `drive_school`.`study_groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `group_name` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `group_name_UNIQUE` (`group_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `drive_school`.`lessons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `drive_school`.`lessons` ;

CREATE TABLE IF NOT EXISTS `drive_school`.`lessons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `groups_id` INT NOT NULL,
  `instructors_users_id` INT NOT NULL,
  `lesson_types_id` INT NOT NULL,
  `auditories_number` INT NOT NULL,
  `cars_id` INT NULL DEFAULT NULL,
  `time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_lessons_instructors1_idx` (`instructors_users_id` ASC) VISIBLE,
  INDEX `fk_lessons_lesson_types1_idx` (`lesson_types_id` ASC) VISIBLE,
  INDEX `fk_lessons_auditories1_idx` (`auditories_number` ASC) VISIBLE,
  INDEX `fk_lessons_car1_idx` (`cars_id` ASC) VISIBLE,
  INDEX `fk_lessons_study_groups_idx` (`groups_id` ASC) VISIBLE,
  CONSTRAINT `fk_lessons_auditories1`
    FOREIGN KEY (`auditories_number`)
    REFERENCES `drive_school`.`auditories` (`number`),
  CONSTRAINT `fk_lessons_car1`
    FOREIGN KEY (`cars_id`)
    REFERENCES `drive_school`.`cars` (`id`),
  CONSTRAINT `fk_lessons_instructors1`
    FOREIGN KEY (`instructors_users_id`)
    REFERENCES `drive_school`.`instructors` (`users_id`),
  CONSTRAINT `fk_lessons_lesson_types1`
    FOREIGN KEY (`lesson_types_id`)
    REFERENCES `drive_school`.`lesson_types` (`id`),
  CONSTRAINT `fk_lessons_study_groups`
    FOREIGN KEY (`groups_id`)
    REFERENCES `drive_school`.`study_groups` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `drive_school`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `drive_school`.`users` ;

CREATE TABLE IF NOT EXISTS `drive_school`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(32) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(32) NOT NULL,
  `middle_name` VARCHAR(32) NULL DEFAULT NULL,
  `last_name` VARCHAR(32) NOT NULL,
  `phone_number` VARCHAR(20) NOT NULL,
  `email` VARCHAR(32) NOT NULL,
  `pass_number` VARCHAR(10) NOT NULL,
  `registration_date` DATETIME NOT NULL,
  `role` VARCHAR(1) NOT NULL DEFAULT 's' COMMENT 's = student\\ni = instructor',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  UNIQUE INDEX `phone_number_UNIQUE` (`phone_number` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `pass_number_UNIQUE` (`pass_number` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `drive_school`.`students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `drive_school`.`students` ;

CREATE TABLE IF NOT EXISTS `drive_school`.`students` (
  `users_id` INT NOT NULL AUTO_INCREMENT,
  `study_start_date` DATETIME NOT NULL,
  `exam_date` DATETIME NOT NULL,
  `groups_id` INT NOT NULL,
  PRIMARY KEY (`users_id`),
  UNIQUE INDEX `users_id_UNIQUE` (`users_id` ASC) VISIBLE,
  INDEX `fk_students_users_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_students_group_idx` (`groups_id` ASC) VISIBLE,
  CONSTRAINT `fk_students_group`
    FOREIGN KEY (`groups_id`)
    REFERENCES `drive_school`.`study_groups` (`id`),
  CONSTRAINT `fk_students_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `drive_school`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `drive_school`.`tests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `drive_school`.`tests` ;

CREATE TABLE IF NOT EXISTS `drive_school`.`tests` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `author_id` INT NULL DEFAULT NULL,
  `image` BLOB NULL DEFAULT NULL,
  `text` VARCHAR(1000) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `var1` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `var2` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `var3` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `var4` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `true_var_number` INT NOT NULL DEFAULT '1' COMMENT '1-4 - ttrue option',
  `answer_comment` VARCHAR(1000) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;

USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`auditories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`auditories` ;

CREATE TABLE IF NOT EXISTS `mydb`.`auditories` (
  `number` INT NOT NULL,
  PRIMARY KEY (`number`),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`cars`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cars` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cars` (
  `id` INT NOT NULL,
  `model` VARCHAR(32) NULL DEFAULT NULL,
  `plate` VARCHAR(20) NOT NULL,
  `bought_date` DATE NOT NULL,
  `bought_price` INT NULL DEFAULT NULL,
  `status` VARCHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `plate_UNIQUE` (`plate` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`groups` ;

CREATE TABLE IF NOT EXISTS `mydb`.`groups` (
  `id` INT NOT NULL,
  `group_name` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `group_name_UNIQUE` (`group_name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL,
  `login` VARCHAR(32) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(32) NOT NULL,
  `middle_name` VARCHAR(32) NULL DEFAULT NULL,
  `last_name` VARCHAR(32) NOT NULL,
  `phone_number` VARCHAR(20) NOT NULL,
  `email` VARCHAR(32) NOT NULL,
  `pass_number` VARCHAR(10) NOT NULL,
  `registration_date` DATE NOT NULL,
  `role` VARCHAR(1) NOT NULL DEFAULT 's' COMMENT 's = student\\ni = instructor',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  UNIQUE INDEX `phone_number_UNIQUE` (`phone_number` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `pass_number_UNIQUE` (`pass_number` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`instructors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`instructors` ;

CREATE TABLE IF NOT EXISTS `mydb`.`instructors` (
  `users_id` INT NOT NULL,
  `hired_date` DATE NOT NULL,
  `salary` INT NOT NULL,
  `last_holiday_start_date` DATE NULL DEFAULT NULL,
  `last_holiday_end_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`users_id`),
  UNIQUE INDEX `users_id_UNIQUE` (`users_id` ASC) VISIBLE,
  INDEX `fk_instructors_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_instructors_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`lesson_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`lesson_types` ;

CREATE TABLE IF NOT EXISTS `mydb`.`lesson_types` (
  `id` INT NOT NULL,
  `name` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`lessons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`lessons` ;

CREATE TABLE IF NOT EXISTS `mydb`.`lessons` (
  `id` INT NOT NULL,
  `groups_id` INT NOT NULL,
  `instructors_users_id` INT NOT NULL,
  `lesson_types_id` INT NOT NULL,
  `auditories_number` INT NOT NULL,
  `cars_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_lessons_groups1_idx` (`groups_id` ASC) VISIBLE,
  INDEX `fk_lessons_instructors1_idx` (`instructors_users_id` ASC) VISIBLE,
  INDEX `fk_lessons_lesson_types1_idx` (`lesson_types_id` ASC) VISIBLE,
  INDEX `fk_lessons_auditories1_idx` (`auditories_number` ASC) VISIBLE,
  INDEX `fk_lessons_cars1_idx` (`cars_id` ASC) VISIBLE,
  CONSTRAINT `fk_lessons_auditories1`
    FOREIGN KEY (`auditories_number`)
    REFERENCES `mydb`.`auditories` (`number`),
  CONSTRAINT `fk_lessons_cars1`
    FOREIGN KEY (`cars_id`)
    REFERENCES `mydb`.`cars` (`id`),
  CONSTRAINT `fk_lessons_groups1`
    FOREIGN KEY (`groups_id`)
    REFERENCES `mydb`.`groups` (`id`),
  CONSTRAINT `fk_lessons_instructors1`
    FOREIGN KEY (`instructors_users_id`)
    REFERENCES `mydb`.`instructors` (`users_id`),
  CONSTRAINT `fk_lessons_lesson_types1`
    FOREIGN KEY (`lesson_types_id`)
    REFERENCES `mydb`.`lesson_types` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`students` ;

CREATE TABLE IF NOT EXISTS `mydb`.`students` (
  `users_id` INT NOT NULL,
  `study_start_date` DATE NOT NULL,
  `exam_date` DATE NOT NULL,
  `groups_id` INT NOT NULL,
  PRIMARY KEY (`users_id`),
  UNIQUE INDEX `users_id_UNIQUE` (`users_id` ASC) VISIBLE,
  INDEX `fk_students_users_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_students_groups1_idx` (`groups_id` ASC) VISIBLE,
  CONSTRAINT `fk_students_groups1`
    FOREIGN KEY (`groups_id`)
    REFERENCES `mydb`.`groups` (`id`),
  CONSTRAINT `fk_students_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `drive_school` ;

-- -----------------------------------------------------
-- Placeholder table for view `drive_school`.`lessons_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drive_school`.`lessons_view` (`instructor_name` INT, `group_name` INT, `group_id` INT, `id` INT, `aud_number` INT, `lesson_time` INT, `lesson_type_name` INT);

-- -----------------------------------------------------
-- View `drive_school`.`lessons_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `drive_school`.`lessons_view`;
DROP VIEW IF EXISTS `drive_school`.`lessons_view` ;
USE `drive_school`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `drive_school`.`lessons_view` AS select concat_ws(' ',`u`.`first_name`,coalesce(`u`.`middle_name`,''),`u`.`last_name`) AS `instructor_name`,`g`.`group_name` AS `group_name`,`l`.`groups_id` AS `group_id`,`l`.`id` AS `id`,`l`.`auditories_number` AS `aud_number`,`l`.`time` AS `lesson_time`,`lt`.`name` AS `lesson_type_name` from ((((`drive_school`.`lessons` `l` join `drive_school`.`study_groups` `g` on((`l`.`groups_id` = `g`.`id`))) join `drive_school`.`instructors` `i` on((`l`.`instructors_users_id` = `i`.`users_id`))) join `drive_school`.`users` `u` on((`l`.`instructors_users_id` = `u`.`id`))) join `drive_school`.`lesson_types` `lt` on((`l`.`lesson_types_id` = `lt`.`id`)));
USE `drive_school`;

DELIMITER $$

USE `drive_school`$$
DROP TRIGGER IF EXISTS `drive_school`.`set_registration_date` $$
USE `drive_school`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `drive_school`.`set_registration_date`
BEFORE INSERT ON `drive_school`.`users`
FOR EACH ROW
BEGIN 
    SET NEW.registration_date = CURDATE(); 
END$$


USE `drive_school`$$
DROP TRIGGER IF EXISTS `drive_school`.`students_BEFORE_INSERT` $$
USE `drive_school`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `drive_school`.`students_BEFORE_INSERT`
BEFORE INSERT ON `drive_school`.`students`
FOR EACH ROW
BEGIN
	SET NEW.study_start_date = CURDATE();
    SET NEW.exam_date = DATE_ADD(CURDATE(), INTERVAL 90 DAY); 
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
